### ISSUE TITLE
Viewing and accessing saved results

### ISSUE THREAD

**Issue by 5183nischal** [alcrene/smttask#6]
Hey, cool tool! I am trying to give it a go and I had a quick question: If I have recorded tasks, their params and output using `@RecordedTask`, how can I (ideally in python or in cli) look at all the recorded tasks and load them? It wasn't clear to me from the docs. 

Thanks!

**Comment by alcrene** [comment]
Hi! There is actually support for both Python and CLI exploration, but some of the relevant documentation pages weren’t being included in the build.

I’ve updated the docs now so that they cover most of what is possible.

- The [Quick Start page](https://sumatratask.readthedocs.io/en/main/getting_started/quickstart.html#exploring-recorded-tasks) has a section with relevant links.
- The [In-depth page](https://sumatratask.readthedocs.io/en/main/in_depth/Exploring%20recorded%20tasks.html) – which previously was being excluded from builds – is now accessible. It’s a bit out of date but still a good overview I think.
- The new [API page](https://sumatratask.readthedocs.io/en/main/user-api/rsview.html) is auto-generated so should always be up-to-date.

There is also a complementary CLI interface, with functionality more aligned with batch processing records. Its API is now much better documented as well; you can find that [here](https://sumatratask.readthedocs.io/en/main/user-api/cli.html#api-cli-store).

I know that it’s still not the most polished documentation, so if there’s anything else I can clarify, or something you’re not quite sure how to do, feel free to ask.

**Comment by 5183nischal** [comment]
This is great, I will continue experimenting with it and ask if I face problems! Thank you for the quick response.
